--HAVING  é o famoso FILTRO DO GROUP BY, É COMO SE FOSSE O WHERE DO WHERE 


--INNER JOIN
SELECT A1_NOME, SUM(F2_VALBRUT) TOTALVENDA FROM SA1990 SA1, SF2990 SF2
WHERE SA1.A1_COD = SF2.F2_CLIENTE AND SA1.A1_LOJA = SF2.F2_LOJA
AND SF2.D_E_L_E_T_ = ' ' AND SA1.D_E_L_E_T_ = ' '

GROUP BY  A1_NOME

HAVING SUM(F2_VALBRUT) > 100



