--TRANSFORMANDO QUERY EM COLUNA

SELECT
A1_COD,
A1_LOJA,
A1_NOME,
ISNULL((SELECT SUM(F2_VALBRUT) TOTALVENDA 
FROM SF2990 SF2
WHERE SA1.A1_COD = SF2.F2_CLIENTE AND SA1.A1_LOJA = SF2.F2_LOJA AND SF2.D_E_L_E_T_ = ' '
GROUP BY F2_CLIENTE+F2_LOJA
),0) TOTALDEVENDA

FROM SA1990 SA1

----