#include 'totvs.ch'
#include 'protheus.ch'

/*/{Protheus.doc} zMsAdvsize
description
@type function
@version  
@author arthu
@since 26/11/2021
@return variant, return_description
@see http://efacildemais.blogspot.com/2011/06/msadvsize-dimensionamento-de-janelas-no.html
@see https://tdn.totvs.com/display/tec/Construtor+TDialog%3ANew
@see https://tdn.totvs.com/display/tec/Construtor+TButton%3ACreate
@see https://tdn.totvs.com/display/tec/TSay
@see https://tdn.totvs.com/display/tec/TDialog
/*/
User Function zMsAdvsize()
  Local oDlg1 // Variavel que recebera a chamada da classe TDialog
  Local cTituloJanela := 'Utilitários do Protheus'
  Local oButton1 // variavel que recebera a classe do primeiro botao
  Local oButton2 // variavel que recebera a classe do segundo botao
  Local oButton3 // variavel que recebera a classe do terceiro botao
  Local oButton4
  Local oButton5
  Local oSay1, oSay2 // variavel que armanazera o say
  Local aSize := MsAdvsize()
  Local cSize7, cSize1, cSize6, cSize5

  cSize7 := cValTochar(aSize[7])
  cSize1 := cValToChar(aSize[1])
  cSize6 := cValToChar(aSize[6])
  cSize5 := cValTochar(aSize[5])

  oDg1 := TDialog():New(aSize[7],aSize[1],aSize[6],aSize[5],cTituloJanela,,,,,CLR_BLACK,CLR_WHITE,,,.T.)
  
  oButton1 := TButton():New(20,20,"Clientes",oDlg1,{||Mata030()}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. ) // chama tela de clientes
  oSay1 := TSay():New(25,70,{||'Clientes'},oDlg1,,,,,,.T.,CLR_BLACK,CLR_WHITE,300,20)
  
  oButton2 := TButton():New(40,40,"Fornecedores",oDlg1,{||Mata020()}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. ) // chama tela de fornecedores
  oSay2 := TSay():New(45,95,{||'Fornecedores'},oDlg1,,,,,,.T.,CLR_BLACK,CLR_WHITE,300,20)
  
  oButton3 := TButton():New(60,60,"Bancos",oDlg1,{||Mata070()}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. ) // chama tela de fornecedores
  oButton4 := TButton():New(80,80,"Produtos",oDlg1,{||Mata010()}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. ) // chama tela de fornecedores
  oButton5 := TButton():New(100,100,"FECHAR",oDlg1,{||oDg1:End()}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. ) // chama tela de fornecedores

  oSaySize    := TSay():New(120,20,{|| cSize7+"   "+cSize1+"   "+cSize6+"   "+cSize5},oDlg1,,,,,,.T.,CLR_RED,CLR_WHITE,400,20)

  oDg1:Activate(,,,.F.)
Return 
