#include 'protheus.ch'
#include 'totvs.ch'

User Function zTComboBox()
  Local oDlg1
  Local aOpcoes := {"Feliz", "Animado", "Eufórico", "Pensativo"}
  Local cOpcao := aOpcoes[2]
  Local oCombo1
  Local oButton1

  oDlg1 := TDialog():New(0,0,410,410,'Cadastro de Funcionarios',,,,,CLR_BLACK,CLR_WHITE,,,.T.)

  oCombo1 := TComboBox():New(02,02,{|u|if(PCount()>0,cOpcao:=u,cOpcao)},;
        aOpcoes,100,20,oDlg1,,{||Alert('Mudou item da combo' + cOpcao)};
        ,,,,.T.,,,,,,,,,'cOpcao')

  oButton1 := TButton():New(50,20,"Mostrar",oDlg1,{||MsgInfo(cOpcao, "Hoje vc está")}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. )

  oDlg1:Activate(,,,.T.)
Return 
