#include 'totvs.ch'
#include 'protheus.ch'

User Function zTGet()
  Local oDlg1
  Local oSay1
  Local oSay2
  Local oButton1

  // Codigo
  Local cGet1 := Space(6)
  Local oGet1

  // Loja
  Local cGet2 := Space(2)
  Local oGet2
  

  oDlg1 := TDialog():New(0,0,200,500,'BLOQUEADOR DE CLIENTES',,,,,CLR_BLACK,CLR_WHITE,,,.T.)

  oSay1 := TSay():New(10,10,{||'Digite seu nome'},oDlg1,,,,,,.T.,CLR_BLACK,CLR_WHITE,300,20)
  oGet1 := TGet():New(25,10,{|u| IF(Pcount()>0,cGet1:=u,cGet1)},oDlg1,40,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet1,,,,)
  oGet1:cF3 := "SA1"

  oSay2 := TSay():New(10,60,{||'Digite seu nome'},oDlg1,,,,,,.T.,CLR_BLACK,CLR_WHITE,300,20)
  oGet2 := TGet():New(25,60,{|u| IF(Pcount()>0,cGet2:=u,cGet2)},oDlg1,30,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet1,,,,)
  
  oButton1 := TButton():New(60,10,"Bloquear agora",oDlg1,{|| fBlock(cGet1,cGet2)}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. )
  
  oDlg1:Activate(,,,.T.)
Return 

Static Function fBlock(cCod, cLoja)
  dbSelectArea("SA1")
  SA1->(dbSeek(xFilial("SA1")+cCod+cLoja))

  RecLock("SA1", .F.)
    SA1->A1_MSBLQL := '1'
  MsUnlock()

  MsgInfo("O cliente com código "+cCod+"e loja "+cLoja+" foi bloqueado com sucesso!", "ATENÇÃO")
Return 
