#include 'protheus.ch'
#include 'totvs.ch'

/*/{Protheus.doc} User Function zTGroup
  {
  (long_description)
  @type  Function
  @author user
  @since 26/11/2021
  @version version
  @param , param_type, param_descr
  @return , return_type, return_description
  @example
  (examples)
  @see (links_or_references)
  /*/
User Function zTGroup()
  Local oDlg1
  Local oButton1, oButton2
  Local oGroup1, oGroup2
  Private cGet1, cGet2, cGet3, cGet4
  Private oGet1, oGet2, oGet3, oGet4

  cGet1 := Space(30)
  cGet2 := Space(30)
  cGet3 := Space(30)
  cGet4 := Space(30)
  
  oDlg1 := TDialog():New(0,0,410,410,'Cadastro de Funcionarios',,,,,CLR_BLACK,CLR_WHITE,,,.T.)

  // Group 1
  oGroup1 := TGroup():New(10,10,100,200,'Group 1',oDlg1,,,.T.)
  oGet1 := TGet():New(30,30,{|u| IF(Pcount()>0,cGet1:=u,cGet1)},oDlg1,60,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet1,,,,)
  oGet2 := TGet():New(50,30,{|u| IF(Pcount()>0,cGet2:=u,cGet2)},oDlg1,60,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet2,,,,)
  oButton1 := TButton():New(80,30,"Gerar",oDlg1,{|| SendGets()},60,15,,,.F.,.T.,.F.,,.F.,,,.F. )

  // Group 2
  oGroup2 := TGroup():New(110,10,200,200,'Group 2',oDlg1,,,.T.)
  oGet3 := TGet():New(130,30,{|u| IF(Pcount()>0,cGet3:=u,cGet3)},oDlg1,60,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.T.,.F.,,cGet3,,,,)
  oGet4 := TGet():New(150,30,{|u| IF(Pcount()>0,cGet4:=u,cGet4)},oDlg1,60,10,"@!",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.T.,.F.,,cGet4,,,,)
  oButton2 := TButton():New(180,30,"Fechar",oDlg1,{|| oDlg1:End()},60,15,,,.F.,.T.,.F.,,.F.,,,.F. )

  oDlg1:Activate(,,,.T.)
Return

Static Function SendGets()
  cGet3 := cGet1
  cGet4 := cGet2
  
  oGet3:Refresh()
  oGet4:Refresh()
return
